GET http://localhost:8080/api/posts

###

POST http://localhost:8080/api/posts
Content-Type: application/json

{
  "id": 0,
  "content": "Last Post"
}

###

POST http://localhost:8080/api/posts
Content-Type: application/json

{
  "id": 0,
  "content": "Last+1 Post"
}
###
POST http://localhost:8080/api/posts
Content-Type: application/json

{
"id": 0,
"content": "Last+2 Post"
}

###

DELETE http://localhost:8080/api/posts/1
